$(window).on('load',function(){$('.preloader').slideUp('slow');$('body').removeClass('preloading');commonScripts();mainSlider();mobileExpander();if($('#v0').length){var vid=document.getElementById("v0");vid.play();$('#v0').on('ended',function(){$('#v0').remove();$('.vid-bg-img').addClass('move')})}
setTimeout(function(){$('header').addClass('video-playing')},1000);function videoPlayOnScroll(){if($('#v0').length){var frameNumber=0,playbackConst=500,setHeight=document.getElementById("set-height"),vid=document.getElementById('v0');setHeight.style.height=Math.floor(vid.duration)*playbackConst+"px";isWelcomeVisible();function scrollPlay(){var frameNumber=window.pageYOffset/playbackConst;vid.currentTime=frameNumber;window.requestAnimationFrame(scrollPlay)}
window.requestAnimationFrame(scrollPlay)}}
var hmPortfolioCarousel=$('.hm-portfolio-carousel');var hmPortfolioArgs={items:1,dots:!0,loop:!0,}
slidrerOnlyMobile(hmPortfolioCarousel,1200,hmPortfolioArgs)});var headerElement=$('header');var headerBottomPosition=headerElement.position().top+headerElement.outerHeight(!0);$(window).scroll(function(){var scrollPosition=$(window).scrollTop();if(scrollPosition>headerBottomPosition){$('.navigation').addClass('set-bg')}else{$('.navigation').removeClass('set-bg')}});function isWelcomeVisible(){var getWindowHeight=$(window).innerHeight();$(window).scroll(function(){var bodyScrollPosition=$(window).scrollTop();var welcomeScrollPosition=$('#hm-welcome').offset().top;var welcomePosition=welcomeScrollPosition-getWindowHeight;if(bodyScrollPosition<welcomePosition){$('header').addClass('video-playing')}else{$('header').removeClass('video-playing')}})}
$(document).ready(function(){var $mainMenuState=$('#main-menu-state');if($mainMenuState.length){$mainMenuState.change(function(e){var $menu=$('#main-menu');if(this.checked){$menu.hide().slideDown(250,function(){$menu.css('display','')})}else{$menu.show().slideUp(250,function(){$menu.css('display','')})}});$(window).on('beforeunload unload',function(){if($mainMenuState[0].checked){$mainMenuState[0].click()}})}
var windowInnerHeight=$(window).innerHeight();$('.main-banner.home-page').css('height',windowInnerHeight);$(window).resize(function(){var windowInnerHeight=$(window).innerHeight();$('.main-banner.home-page').css('height',windowInnerHeight)});var blockTween1=TweenMax.to('#hm-welcome',1.5,{backgroundColor:'#040415'});var controller=new ScrollMagic.Controller();var containerScene1=new ScrollMagic.Scene({triggerElement:'#hm-welcome'}).setTween(blockTween1);controller.addScene([containerScene1]);var revealElements=document.getElementsByClassName("single-portfolio");for(var i=0;i<revealElements.length;i++){new ScrollMagic.Scene({triggerElement:revealElements[i],offset:50,triggerHook:0.9,}).setClassToggle(revealElements[i],"visible").addTo(controller)}
var astronautTimeline=new TimelineLite().add(TweenMax.to(".astronaut",1,{css:{scale:.1,opacity:0,left:'-100%',top:'100%'}}),"first").add(TweenMax.to(".earth",1,{y:'-100%'}),"first");var astronautScene=new ScrollMagic.Scene({triggerElement:"#set-height",triggerHook:'onLeave',duration:3000}).setTween(astronautTimeline).addTo(controller);var astronaut1Move=new TimelineLite().add(TweenMax.to(".astronaut-1",1,{x:'-800%',y:'-800%'}),"first")
var astronaut1Scene=new ScrollMagic.Scene({triggerElement:"#hm-welcome",triggerHook:'onLeave',duration:6000,offset:-800,}).setTween(astronaut1Move).addTo(controller);var rocket1Move=new TimelineLite().add(TweenMax.to(".rocket-1",1,{x:'1600%',y:'-1000%'}),"first");var rocket1Scene=new ScrollMagic.Scene({triggerElement:"#hm-pricing",triggerHook:'onLeave',duration:6000,offset:-400,}).setTween(rocket1Move).addTo(controller);$('.acc-trigger').on('click',function(){$('.acc-trigger').not(this).removeClass('active');$(this).toggleClass('active');$('.acc-trigger').not(this).parent().find('.acc-content').slideUp();$(this).parent().find('.acc-content').slideToggle()})});$(window).on('resize',function(event){});function mainSlider(){if(rest_of_slide.length){var mainSliderArgs={items:1,dots:!1,nav:!1,autoplay:!0,autoplayTimeout:10000,loop:!0,animateIn:'fadeIn',animateOut:'fadeOut',responsive:{1200:{dots:!1,nav:!0}}}
$('.main-banner').append(rest_of_slide).owlCarousel(mainSliderArgs)}}
function commonScripts(){}
function slidrerOnlyMobile(elem,breakpoint,args){if($(elem)[0]){var s=$(elem);if(window.innerWidth<breakpoint){s.owlCarousel(args)}else s.addClass("off");$(window).resize(function(e){if(window.innerWidth<breakpoint){if($(elem).hasClass("off")){s.owlCarousel(args);s.removeClass("off")}}else $(elem).hasClass("off")||(s.addClass("off").trigger("destroy.owl.carousel"),s.find(".owl-stage-outer").children(":eq(0)").unwrap())})}}
function mobileExpander(){var svgElePlus='<svg width="30" height="30" aria-hidden="true"><use xmlns:xlink="http://www.w3.org/1999/xlink"  xlink:href="#menu_plus"></use></svg>';var svgEleMinus='<svg width="30" height="30" aria-hidden="true"><use xmlns:xlink="http://www.w3.org/1999/xlink"  xlink:href="#menu_minus"></use></svg>';$('#main-menu li').each(function(){if($(this).hasClass('menu-item-has-children')){$(this).find('a').first().after('<div class="expicon">'+svgElePlus+'</div>')}});if(window.matchMedia("(min-width: 1200px)").matches){$("#main-menu li").each(function(){if($(this).hasClass('menu-item-has-children')){$(this).addClass('hasExpanded')}});$('.hasExpanded').mouseenter(function(){$(this).find('.expicon').first().html(svgEleMinus);$(this).find('.sub-menu').slideDown()});$('.hasExpanded').mouseleave(function(){$(this).find('.expicon').first().html(svgElePlus);$(this).find('.sub-menu').slideUp()})}else{$('.menu-item-has-children .expicon').on('click',function(){$(this).parent().find('.sub-menu').first().slideToggle();$(this).toggleClass('active');if($(this).hasClass('active')){$(this).html(svgEleMinus)}else{$(this).html(svgElePlus)}})}}
if(window.matchMedia("(min-width: 1200px)").matches){}
;